---
title: "課?<a0>?練習模<e7><89><88>"
author: "Joyce"
date: "2020-12-02"
output: output_format
params:
  id: "410973049"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

##4.7.2 Modify levels

當電腦已懂類別資料，要：

#對原先類別給予不同稱呼
並不需要再用到parsing函數factor, 只需要透過：

```{r}
old_fct <- 
  factor(c("4以下","5-10","11-15"))
levels(old_fct) # 依序下的各類別名稱
```

```{r}
levels(old_fct) <- c("青少年", "幼兒", "兒童")
levels(old_fct)
old_fct
```

# M 改成男 F 改成女 直接對原先類別給予不同稱呼

```{r}
set.seed(2018)
gender<-
  sample(c("M","F"),10000,replace=T)
head(gender)
```

```{r}
gender_fct <- factor(
  gender
  ) # 讓電腦懂這是類別資料
levels(gender_fct) # 出現類別 代表電腦以理解
```

```{r}
levels(gender_fct)<-c("女","男")
head(gender_fct)
```
# 取名稱(屬性) 改元素名稱 names()
```{r}
a <- c(178,172)
names(a)
names(a) <-c("John","Mary")
a
a[["John"]]
```

## levels() <-是用來改變稱呼，千萬不能用它來改各類別排序

```{r}
old_fct2 <- 
  factor(c("4以下","5-10","11-15", "5-10"))
levels(old_fct2)
levels(old_fct2) <- c("4以下","5-10","11-15") #改變名稱 而非順序
old_fct2

#若要改順序
old_fct2 <- 
  factor(c("4以下","5-10","11-15", "5-10"))

old_fct2 <-factor(
  old_fct2,
  levels = c("4以下","5-10","11-15")
)
levels(old_fct2)
old_fct2
```

# 4.7.2.2 整併

```{r}
set.seed(2020)
ages_chr <- sample(c("4以下","5-9","10-14", "15-19"), 20, replace=T)
ages_chr
```

```{r}
ages_fctBy5 <- 
  factor(
    ages_chr,
    levels = c("4以下","5-9","10-14", "15-19")
  )

levels(ages_fctBy5)
table(ages_fctBy5)
```
# 將相同類別名稱皆歸為同類
```{r}
# 改名levels()<-
levels(ages_fctBy5) <- c("10以下", "10以下", "10以上", "10以上")
table(ages_fctBy5)
```
# 4.7.3 增加資料

```{r}

```

