---
title: "課?<a0>?練習模<e7><89><88>"
author: "Joyce"
date: "2020-10-14"
output: output_format
params:
  id: "410973049"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
"\u0928\u092e\u0938\u094d\u0924\u0947 \u0926\u0941\u0928\u093f\u092f\u093e"
```

```{r}
num <- c(1.5, 2, 3)
int <- c(1L, 3L, -2L)#整數
char <- c("1.5","2","3")#字串
logi <- c(T,T,F)

typeof(num)
typeof(int)
typeof(char)
typeof(logi)
```

```{r}
class(num)
class(int)
class(char)
class(logi)
```

```{r}
"1"+"1.5"#二元運算子中有非數值引數 "字串"不能相加
1+1.5
```

```{r}
class("1")
class("1.5")
```

```{r}
as.numeric("1")
```

```{r}
a <- "1" # a被字串取代 " "加双引號為字串
a <-  1  # 指示a為數字1
as.numeric(a) # 若用一開始用a <- "1" 這時已經沒有a 已經被1取代 所以要回存a (->a)
a+4
```
# 以下為分隔線
##---------------------------------------------------------

## charcter
```{r}
# 10位學生的主系
majors10_char <- c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')

typeof(majors10_char)
class(majors10_char)
```

## factor
```{r}
# 10位學生的主系
majors10_factor <- factor(
  c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
)
# or
majors10_factor <- factor(majors10_char)

typeof(majors10_factor)
class(majors10_factor)
```

```{r}
majors10_char
majors10_factor
```

```{r}
as.integer(majors10_factor) 
```

```{r}
a <- factor(c("一","二","三"))
a
```

```{r}

```
