---
title: "課?<a0>?練習模<e7><89><88>"
author: "Joyce"
date: "2020-12-23"
output: output_format
params:
  id: "410973049"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

## 5.1.1
# Block programming

```{r}
# Given some information
R <- 0.09
M <- 10000
T <- 3
# What I need to do
PDV <- 
{
  M/(1+R)**T
}
```

# Function

```{r}
getPDV <- function(R,M,T) 
{
  M/(1+R)**T
}
```

```{r}
getPDV(R=0.09, T=3, M=10000)
```

## 5.1.2 Execution Environment

```{r}
debug(getPDV) 
getPDV(R=0.09, T=3, M=10000) 
undebug(getPDV)
```

## 5.1.3 Function components

```{r}
# 查詢函數formals arguments要求
formals(getPDV)
```

```{r}
# 查詢函數主體
body(getPDV)
```

```{r}
# body執行時若有物件不存在execution environment時要去找尋的environment
environment(getPDV)
```

## 5.1.4 Function Environment

```{r}
# Given some information
T <- 3
# What I need to do
getPDV2 <- function(R,M){
  M/(1+R)**T
}
```

```{r}
getPDV2(R=0.12, M=50000)
debug(getPDV2)
getPDV2(R=0.12, M=50000)
undebug(getPDV2)
```

```{r}
T <- 3
getPDV2(R=0.12, M=50000)
```

```{r}
T <- 1
getPDV2(R=0.12, M=50000)
```

```{r}
globalX <- c(2,5)
testfun <- function(){
  globalX[[2]] <- -1
  invisible(3+globalX)
}
testfun()
globalX
```

```{r}
debug(testfun)
testfun()
undebug(testfun)
```

##5.1.5 Return
```{r}
testFun <- function(){
  a <-2
  b <- 5
  a+b
}
testFun()
```

```{r}
testErrorFun <- function(){
  a <-2
  b <- 5
  output <- a+b
}
testErrorFun()
```

```{r}
testFun <- function(){
  a <-2
  b <- 5
  return(a+b)
}
testFun()
```

