---
title: "課?<a0>?練習模<e7><89><88>"
author: "Joyce"
date: "2020-12-30"
output: output_format
params:
  id: "410973049"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

#5.1.7 Applications

星座查詢

```{r}
library(lubridate); library(dplyr); library(stringr); library(purrr)
jsonlite::fromJSON(
"https://www.dropbox.com/s/8sftw4bbjumeqph/signMapping.json?dl=1") -> horoscopes
```

Step1: Block programming

```{r}
userBirthday <- 
  
  
userHoroscopes <- 
  {
    
  }
```

Block programming in details (pseudo-codes):

```{r}
userBirthday <- ymd("1998-10-30")

userHoroscopes <- 
  {
    # 取得生日年份
    birthYear <- {
      
    }
    
    # 取得生日年份的12星座起始日期
    horoscopeStartingDateInBirthYear <- {
      
    }
    
    # 切割生日成為12星座區間
    cutBirthdayByStartingDate <- {
      
    }
    
    # 改變星座區間類別名稱
    birthdayCutRenameLevels <- {
      
    }
    levels(cutBirthdayByStartingDate) <- birthdayCutRenameLevels
    
    as.character(cutBirthYearByStartingDate)
  }
```

Step2: Turn block programs into function

```{r}
userBirthday <- ymd("1998-10-30")

get_userHoroscopes <- function(userBirthday)
  {
    # 取得生日年份
    birthYear <- {
      year(userBirthday)
    }
    
    # 取得生日年份的12星座起始日期
    horoscopeStartingDateInBirthYear <- {
      str_startingDate <- 
        paste0(birthYear,"-",horoscopes$sdate)
      ymd(str_startingDate)
    }
    
    # 切割生日成為12星座區間
    cutBirthdayByStartingDate <- {
      cut(userBirthday,
          breaks =
            c(
              ymd(
                paste0(birthYear, "-01-01")
              ),
              horoscopeStartingDateInBirthYear,
              Inf
            )
          )
    }
    
    # 改變星座區間類別名稱
    birthdayCutRenameLevels <- {
      c("摩羯座", horoscopes$sign)
    }
    levels(cutBirthdayByStartingDate) <- birthdayCutRenameLevels
    
    as.character(cutBirthdayByStartingDate)
  }
```

Step3: Test your function

```{r}
get_userHoroscopes(ymd("1995-08-27"))
get_userHoroscopes(ymd("1970-05-18"))
get_userHoroscopes(ymd("2001-4-1"))
```

