---
title: "課?<a0>?練習模<e7><89><88>"
author: "Joyce"
date: "2020-10-20"
output: output_format
params:
  id: "410973049"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
library(lubridate)
```

```{r}
tpeTime <- ymd_hms("2020-03-18 13:52:40",
        tz="Asia/Taipei") # 年月日_時分秒
```

```{r}
pgTime <- mdy_hms("Mar.18, 2020, 05:52:40",
                  tz="Europe/Lisbon") #月日年_時分秒
```

```{r}
tpeTimeVector <- 
  ymd_hms(
    c("2020-03-18 13:52:40",
      "2020-03-11 03:12:40"),
    tz="Asia/Taipei"
    )
```

## type/class

```{r}
typeof(tpeTime ) # double 數值裡面非整數的儲存方式
class(tpeTime) # ct 日期 t time
```

```{r}
tpeTime
print(tpeTime) # 以此形式印給人看 字串
cat(tpeTime) # 呈現背後電腦怎麼存 反映電腦記憶的值 
 # 秒數 指和一個時間的原點(1970年1月1日 00:00:00)來比過了多少秒
```
```{r}
as.numeric(tpeTime)
```

```{r}
print(as.character(tpeTime)) # 沒有時區
cat(as.character(tpeTime)) # 給人閱讀
```
## let computer tell us time

Human tells computer

```{r}
tpeTime2 <- ymd_hms("2010-03-18 16:52:40",
        tz="Asia/Taipei")
pgTime2 <- mdy_hms("Mar.01, 2020, 03:52:40",
                  tz="Europe/Lisbon")
```

computer tells human
```{r}
tpeTime3 <- with_tz(tpeTime2, tzone="America/New_York") #重新換成想要的時區
tpeTime2
tpeTime3
typeof(tpeTime3)
class(tpeTime3)
```

"2010-03-18 16:52:40" taipei 

```{r}
tpeTime2
```

"2010-03-18 16:52:40" taipei => New York # 同時間 不同時區
```{r}
tpeTime3
```

```{r}
cat(tpeTime2)
cat(tpeTime3) # 秒數一樣 = 時間一樣
```

```{r}
pgTime3 <- 
  with_tz(pgTime2, tzone="America/New_York")

pgTime2
pgTime3
```
```{r}
tpeTime3 # DT: daylight time 日光節約時間 
pgTime3 # ST: standard time 標準（非日光節約時間）
```
```{r}
tpeTime3 - pgTime3 # 轉成同時區相減
```

```{r}
tpeTime2 - pgTime2 #不同時區仍可直接加減
```

```{r}
tpeTime
class(tpeTime)
as.character(tpeTime) #沒時區
```

```{r}
tpeTime_utc <- with_tz(tpeTime,tzone = "UTC")
tpeTime_utc
as.character(tpeTime_utc)
```

```{r}
tpeTime_iso8601 <- format_ISO8601(tpeTime, usetz=T) #把電腦懂得時間 變成字串(符合國際規則)
tpeTime_iso8601
```

```{r}
tpeTime <- ymd_hms(tpeTime_iso8601)
```

## LIST ------------------------------------------------------------
# 可以是不同type的物件值 將不同class紀錄在一起
```{r}
library(lubridate)

# Date/Time class
purchasingTime <- 
  ymd_hms("2020-03-31T13:40:55Z")

# character
location <- "一芳"
item <- "水果茶"

# numeric
quantity <- 2

mingsPurchase <-
  list(
    purchasingTime, 
    location, 
    quantity, 
    item
  ) # 直的列下來
print(mingsPurchase)
```

```{r}
a <- c(2,5,10,16) # 衡的列
print(a)
```
#對物件命名
```{r}
objectName <-
`objectName` <-
```

```{r}
elementName =
`elementName`=
"elementName"=
'elementName'=
```

```{r}
mingsPurchase2 <-
  list(
    time = purchasingTime,
    'location' = location,
    "quantity" = quantity,
    `item name` = item
  )
print(mingsPurchase2)
```

```{r}
heights = c(
  mary=162,
  john=177,
  steve=180
)
```

```{r}
exampleList <-
  list(
    c(4,6,10),
    list("Mary",173),#list可以是不同class list可以是多層次堆疊
    TRUE
  )
print(exampleList)
```

```{r}
example2 <- list(
  list(2,"john"),
  list(3,"mary")
)
print(example2)
```

```{r}
example2c <- c(
  c(2,5),
  c(4,6)
)   #相當於c(2,3,4,6)
print(example2c)
```

```{r}
# 「**2杯**」「**水果茶**」
item1 <- list(
  quantity=2,
  `item name`="水果茶"
)
# 「**1杯**」「**日月紅茶**」
item2 <- list(
  quantity=1,
  `item name`="日月紅茶"
)

mingsPurchase3 <-
  list(
    time = purchasingTime,
    location = location, # 在r裡面 = <- 相同
    items=list(
      item1,
      item2
    )
  )

print(mingsPurchase3)
```

```{r}
student1 <-
  list(
    name = character(),
    id = character(),
    gmail = character(),
    googleClassroom =
      list(
        displayName = character()
      ),
    github =
      list(
        username = character(),
        repoUrl = character()
      ),
    homeworks = list(),
    exams = list(),
    list() # 沒命名的list
  )

names(student1) # 每個元素名稱
length(student1) # 元素個數
```

```{r}
str(student1, 1) # 第一層基本元素架構
```

```{r}
str(student1, 2) # 第二層基本元素架構
```

```{r}
hw1 <- list(
  date=ymd("2020-10-21"),
  grade=10
)
exam1 <- list(
  date=ymd("2020-10-28"),
  grade=50
)
student1 <-
  list(
    name = "Martin",
    id = "007",
    gmail = "mt@gm.ntpu.edu.tw",
    googleClassroom =
      list(
        displayName = "MT L"
      ),
    github =
      list(
        username = "tpemartin",
        repoUrl = "https://github.com/tpemartin/109-1-inclass-practice"
      ),
    homeworks = list(
      hw1
    ),
    exams = list(
      exam1
    ),
    list()
  )

str(student1, 2)
```

```{r}
categoryTemplate = # Template模板
  list(
    categoryName=character(),
    items = list(
    )
  )

saladCat <- 
  list(
    categoryName="沙拉套餐", # 用list 因為不同的class
    items=list(
      list(
        "板煎雞腿排經典凱薩沙拉,203"
      ), 
      list(
        "炙燒鴨胸左胡麻沙拉",
        203
        ),
        list(
        "煙燻鮭魚佐酒醋沙拉",
        203
      )
    )
  )
print(saladCat)
```

```{r}
library(jsonlite) # 不少同學這行會有Error，還記得如何排除嗎？
toJSON(mingsPurchase3)
```

```{r}
mingsPurchase3
```

```{r}
library(jsonlite) 
toJSON(mingsPurchase3)
```

```{r}
save(item2, saladCat,
     file="myObjects.rda")
```



